# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_wnsdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='apnsdevice',
            name='muted_till',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date/Time to mute notifications until'),
        ),
        migrations.AddField(
            model_name='gcmdevice',
            name='muted_till',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date/Time to mute notifications until'),
        ),
        migrations.AddField(
            model_name='wnsdevice',
            name='muted_till',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date/Time to mute notifications until'),
        ),
    ]









